CREATE DATABASE db_redesocial;

USE db_redesocial;

CREATE TABLE tb_usuarios(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Nome VARCHAR(45) NOT NULL,
	Usuario VARCHAR(45) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Url_Foto VARCHAR(100) NOT NULL
);

CREATE TABLE tb_grupos(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Grupo VARCHAR(45) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	Url_Imagem VARCHAR(100) NOT NULL,
	FK_Criador INT NOT NULL,
	FOREIGN KEY (FK_Criador) REFERENCES tb_usuarios (Id)
);

CREATE TABLE tb_inscritos(
	FK_Usuario INT NOT NULL,
	FK_Grupo INT NOT NULL,
	DataHora DATE NOT NULL,
	FOREIGN KEY (FK_Usuario) REFERENCES tb_usuarios (Id),
	FOREIGN KEY (FK_Grupo) REFERENCES tb_grupos (Id)
);

CREATE TABLE tb_postagens(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Titulo VARCHAR(50) NOT NULL,
	Descricao VARCHAR(1000) NOT NULL,
	Url_Imagem VARCHAR(100) NOT NULL,
	Data_Postagem DATE NOT NULL,
	FK_Criador INT NOT NULL,
	FK_Grupo INT NOT NULL,
	FOREIGN KEY (FK_Criador) REFERENCES tb_usuarios (Id),
	FOREIGN KEY (FK_Grupo) REFERENCES tb_grupos (Id)
);